services:
  db: 
    image: postgres

    container_name: db-postgres

    environment:
      - POSTGRES_DB=limit_order_book
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=sample
      - POSTGRES_HOST=localhost
      - SSLMODE=disable

    ports:
      - "5432:5432"

    volumes:
      - db:/var/lib/postgresql

volumes:
    db: